name: mde_flutter
description: A cross platform viewer for the mods.de forum.

version: 0.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.2.1"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ">=0.4.2"

  cupertino_icons: ">=0.1.2"

  html: ">=0.13.4+1"

  intl: ">=0.15.7"

  meta: ">=1.1.6"

  mime: ">=0.9.6+2"

  path: ">=1.6.2"

  path_provider: ">=0.5.0+1"

  reflected_mustache: ">=1.0.11"

  shared_preferences: ">=0.5.1+2"

  url_launcher: ">=5.0.2"

  webview_flutter: ">=0.3.4"

  xml: ">=3.3.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ">=1.5.3"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/banghead.gif
    - assets/icons/biggrin.gif
    - assets/icons/confused.gif
    - assets/icons/freaked.gif
    - assets/icons/hm.gif
    - assets/icons/icon1.gif
    - assets/icons/icon2.gif
    - assets/icons/icon3.gif
    - assets/icons/icon4.gif
    - assets/icons/icon5.gif
    - assets/icons/icon6.gif
    - assets/icons/icon7.gif
    - assets/icons/icon8.gif
    - assets/icons/icon9.gif
    - assets/icons/icon10.gif
    - assets/icons/icon11.gif
    - assets/icons/icon12.gif
    - assets/icons/icon13.gif
    - assets/icons/icon15.gif
    - assets/icons/icon16.gif
    - assets/icons/icon18.gif
    - assets/icons/mata.gif
    - assets/icons/pfeil.gif
    - assets/icons/sceptic.gif
    - assets/icons/sleepy.gif
    - assets/icons/smiley-pillepalle.gif
    - assets/icons/thumbsdown.gif
    - assets/icons/thumbsup.gif
    - assets/icons/ugly.gif
    - assets/icons/urgs.gif
    - assets/icons/wink.gif
    - assets/bender.png
    - assets/board.css
    - assets/board.html
    - assets/board.js
    - assets/boards.js
    - assets/boards.css
    - assets/boards.html
    - assets/error.js
    - assets/error.css
    - assets/error.html
    - assets/jquery.min.js
    - assets/jquery.mobile.custom.min.js
    - assets/material-icons.css
    - assets/material-icons.woff2
    - assets/thread.css
    - assets/thread.html
    - assets/thread.js
